import pandas as pd


def generate_executive_summary(df):
    """
    Generate executive workforce summary report
    """

    total_employees = len(df)

    attrition_count = (df["Attrition"] == "Yes").sum()

    attrition_rate = (attrition_count / total_employees) * 100

    avg_income = df["MonthlyIncome"].mean()

    department_count = df["Department"].nunique()

    overtime_count = (
        df["OverTime"] == "Yes"
    ).sum()

    summary = f"""
EXECUTIVE WORKFORCE INTELLIGENCE REPORT
=======================================

Workforce Overview
------------------
Total Employees: {total_employees}

Number of Departments: {department_count}

Average Monthly Income:
${avg_income:.2f}


Attrition Analysis
------------------
Employees Left: {attrition_count}

Attrition Rate:
{attrition_rate:.2f}%


Engagement Insights
-------------------
Employees Working Overtime:
{overtime_count}


Strategic Recommendations
-------------------------
1. Improve employee engagement programs.

2. Monitor employees with high attrition risk.

3. Create career growth opportunities.

4. Review overtime workload distribution.

=======================================
Generated by AI Workforce Intelligence System
"""

    return summary